#!/usr/bin/env bash
# This script:
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when
# receiving a SIGQUIT or SIGTERM signal

sudo touch /var/run/holbertonscript.pid
sudo bash -c "echo $$ > /var/run/holbertonscript.pid"

function sigterm {
    echo "I hate the kill command"
    sudo rm /var/run/holbertonscript.pid
    exit
}

function sigint {
    echo "Y U no love me?!"
    exit
}

function sigquit {
    sudo rm /var/run/holbertonscript.pid
    exit
}

trap sigterm SIGTERM
trap sigint SIGINT
trap sigquit SIGQUIT

x=1
while [ $x -lt 2 ]
do
	echo "To infinity and beyond indefinitely"
	# sleep 2
done

