#!/usr/bin/env bash
# This script displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

trap "echo I am invincible" SIGTERM
x=1

while [ $x -lt 2 ]
do
	echo "To infinity and beyond"
	sleep 2
done
